version: '2'
services:
  web:
    image: xfanis/odoo:10.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-data-web:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./:/mnt/extra-addons
  db:
    image: postgres:10
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-data-db:/var/lib/postgresql/data/pgdata
volumes:
  odoo-data-web:
  odoo-data-db: