version: '2'
services:
  odoo13:
    image: odoo:11.0
    depends_on:
      - odoo13db
    ports:
      - "8069:8069"
    environment:
      - HOST=odoo13db
    volumes:
      - odoo13-data-web:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./:/mnt/extra-addons
  odoo13db:
    image: postgres:10
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo13-data-db:/var/lib/postgresql/data/pgdata
volumes:
  odoo13-data-web:
  odoo13-data-db: